### ISSUE TITLE
When will it be released, I can't wait to run it

### ISSUE THREAD

**Issue by HelloCxz** [hugochan/IDGL#1]

**Comment by hugochan** [comment]
Hi,

Thank you for your interest to our work! We are currently preparing for releasing the code & data. Please stay tuned! Thanks!

**Comment by yyyzhao** [comment]
Me too.

**Comment by Andy-Border** [comment]
Hi, when will you release the code : ) 
I've been waiting for a long time.

**Comment by hugochan** [comment]
Thank you for your interest to our work! The code has been released.
