### ISSUE TITLE
Questions regarding time complexity

### ISSUE THREAD

**Issue by AndyJZhao** [hugochan/IDGL#12]
Hi, thanks for the insightful work IDGL. 

However, I cannot fully agree with the complexity discussion in the paper. In the paper (Page 5), the paper claims that IDGL-Anch has time and space complexity of O(ns).  Meanwhile, in my humble opinion, the message passing scheme should be far greater than O(ns). 

As stated in the paper, in each $MP_a$ operation, the adjacency matrix is firstly recovered and then used in message passing. The adjacency matrix is recovered by $RowNorm(R) \cdot transpose(ColNorm(R))$, which is already $O(n^2s)$ complexity if two matrices are dense (The time complexity of dense matrix multiplication between mxn and nxp matrix is O(mnp)).

Please kindly correct me if I was wrong. Your time is highly appreciated.

**Comment by hugochan** [comment]
> Hi, thanks for the insightful work IDGL.
> 
> However, I cannot fully agree with the complexity discussion in the paper. In the paper (Page 5), the paper claims that IDGL-Anch has time and space complexity of O(ns). Meanwhile, in my humble opinion, the message passing scheme should be far greater than O(ns).
> 
> As stated in the paper, in each $MP_a$ operation, the adjacency matrix is firstly recovered and then used in message passing. The adjacency matrix is recovered by $RowNorm(R) \cdot transpose(ColNorm(R))$, which is already $O(n^2s)$ complexity if two matrices are dense (The time complexity of dense matrix multiplication between mxn and nxp matrix is O(mnp)).
> 
> Please kindly correct me if I was wrong. Your time is highly appreciated.

@Andy-Border Thanks for your interest to our work! As for the anchor-based approach, the n x n adjacency matrix A is never explicitly computed due to the high complexity (i.e., O(n^2s) as you stated). Instead, message passing on A is implicitly achieved by Eq. (7) in the [paper](https://proceedings.neurips.cc/paper/2020/file/e05c7ba4e087beea9410929698dc41a6-Paper.pdf) with O(ns) complexity.
