### ISSUE TITLE
reproduce ogbn-arxiv

### ISSUE THREAD

**Issue by titaniumrain** [hugochan/IDGL#13]
Quick question on reproducing ogbn-arxiv using IDGL code. May I please quickly ask what your environment looks like? We ran the source code and always hit OOM error. It looks like, if our math is correct, the system requires at least 100GB GPU memory...

**Comment by hugochan** [comment]
> Quick question on reproducing ogbn-arxiv using IDGL code. May I please quickly ask what your environment looks like? We ran the source code and always hit OOM error. It looks like, if our math is correct, the system requires at least 100GB GPU memory...

@titaniumrain Thank you for your interest to our work! We were not able to run IDGL on ogbn-arxiv because the graph was too large. We only evaluated the IDGL-Anch version on ogbn-arxiv. We used a 32GB GPU. 

Hope this helps!

**Comment by titaniumrain** [comment]
@hugochan Thanks for the clarification. I was referring to IDGL-Anch version in my original thread. Let us try again and circle back the results.

**Comment by titaniumrain** [comment]
@hugochan  thanks again for your prompt assistance. We tested the code again and can confirm that IDGL-Anch works. Will close the ticket accordingly.
