### ISSUE TITLE
How are the pictures in the appendix drawn

### ISSUE THREAD

**Issue by AOoligei** [hugochan/IDGL#15]
Hi, 
excellent work. 
I am eager to know how the pictures in the appendix are drawn, because these pictures are so charming and I didn't find it in the code. Can you provide it to me? Thank you.[http://m.qpic.cn/psc?/V14ADfFj30Vktj/TmEUgtj9EK6.7V8ajmQrEEFcmPNruYtCv3LwJgjqOwmRH6lXLjw5wV6z5vuK9TmfVBORolCcbwnXlVINWfGWYMnYf*jRj0BaCeT0l.0euZc!/b&bo=MgMHAzIDBwMDKQw!&rf=viewer_4](url)

**Comment by hugochan** [comment]
> Hi,
> excellent work.
> I am eager to know how the pictures in the appendix are drawn, because these pictures are so charming and I didn't find it in the code. Can you provide it to me? Thank you.[http://m.qpic.cn/psc?/V14ADfFj30Vktj/TmEUgtj9EK6.7V8ajmQrEEFcmPNruYtCv3LwJgjqOwmRH6lXLjw5wV6z5vuK9TmfVBORolCcbwnXlVINWfGWYMnYf*jRj0BaCeT0l.0euZc!/b&bo=MgMHAzIDBwMDKQw!&rf=viewer_4](url)

@AOoligei Thank you for your interest to our work! We used Gephi (https://gephi.org) to plot the graphs.
