### ISSUE TITLE
How to use IDGL on my own dataset?

### ISSUE THREAD

**Issue by Riofd** [hugochan/IDGL#16]
Thank you for your great work! But I have some problems when I use the code on my own dataset. Here are some details:
1) My task is graph classification;
2) The size of my input features is 7000×72×200: 7000 samples and each sample has 72 nodes and the input dimension of each node is 100;
3) The dataset can be divided into 3 classes.
When I set my own config, and it reported "correct = preds.eq(labels).double()
RuntimeError : The size of tensor a (3) must match the size of tensor b (6240) at non-singleton dimension 1". Also I noticed that the output of the GNN is 72×3 for each sample, but it should be 3. Where should I change the code for my dataset? Thank you!

**Comment by hugochan** [comment]
@Riofd Thanks for your interest to our work! As for graph classification use case, you might want to refer to the text graph classification [example](https://github.com/hugochan/IDGL/blob/master/src/core/models/text_graph.py#L173) in this repo. The main difference is in our case, we prepared a kNN graph for each text example while in your case the initial graph of each example is given.

**Comment by jiangxinke** [comment]
Hi, I wanna ask two questions:  1. How I use my own dateset(A graph, and each node is a time series data)  2. Where is the adj matrix hold, I did not find it. THANKS FOR YOUR HELP!

**Comment by hugochan** [comment]
> Hi, I wanna ask two questions: 1. How I use my own dateset(A graph, and each node is a time series data) 2. Where is the adj matrix hold, I did not find it. THANKS FOR YOUR HELP!

@jiangxinke 1) the model was not designed for handling time series data, even though the idea of the model might be extended to time series data. 2) please check out this [code](https://github.com/hugochan/IDGL/blob/master/src/core/model_handler.py#L656) on how to access adj matrix.

**Comment by simona-juv** [comment]
> @Riofd Thanks for your interest to our work! As for graph classification use case, you might want to refer to the text graph classification [example](https://github.com/hugochan/IDGL/blob/master/src/core/models/text_graph.py#L173) in this repo. The main difference is in our case, we prepared a kNN graph for each text example while in your case the initial graph of each example is given.

Hi! I am trying to understand the example to use it for my own dataset, but the 20news data is missing from the repository. Can I download it from somewhere else?

**Comment by hugochan** [comment]
> > @Riofd Thanks for your interest to our work! As for graph classification use case, you might want to refer to the text graph classification [example](https://github.com/hugochan/IDGL/blob/master/src/core/models/text_graph.py#L173) in this repo. The main difference is in our case, we prepared a kNN graph for each text example while in your case the initial graph of each example is given.
> 
> Hi! I am trying to understand the example to use it for my own dataset, but the 20news data is missing from the repository. Can I download it from somewhere else?

Hi @simona-juv , sorry for the late reply! You can download the 20news data at [20news-bydate.tar.gz](http://qwone.com/~jason/20Newsgroups/20news-bydate.tar.gz).
