### ISSUE TITLE
May I ask a question about graph classification? Is it to synthesize multiple graphs in a batch into a large graph (node_vec and adj) into GNN for training?

### ISSUE THREAD

**Issue by yas8086** [hugochan/IDGL#21]
`node_vec = torch.relu(network.encoder.graph_encoders[0](init_node_vec, cur_adj))`
**Can you provide the shape of the init_node_vec and cur_adj?**

**Comment by hugochan** [comment]
Hi @yullll , thanks for the interest to the work! We didn't convert a batch of graphs to a large graph, so the shape of the init_node_vec and cur_adj are (batch_size, num_nodes, dim) and (batch_size, num_nodes, num_nodes).
