### ISSUE TITLE
Bug when I run for 20news

### ISSUE THREAD

**Issue by PKUTAN** [hugochan/IDGL#22]
when I switch to dataset:20news，this bug occurred , and I think it is not a technical bug but missing file?
![343696c6630b93cf6756ea76f662691](https://user-images.githubusercontent.com/101382589/210925262-4264e07c-d57b-444c-9560-b6e358dba338.png)

**Comment by hugochan** [comment]
Hi @PKUTAN , thanks for your interest to the work! This is a placeholder path to the GloVe word2vec file. You will need to change the path to your own GloVe word2vec file (https://nlp.stanford.edu/projects/glove/).
