### ISSUE TITLE
Implementation of Anchor-based graph learning

### ISSUE THREAD

**Issue by shuix007** [hugochan/IDGL#6]
Hi,

Great work. Do you also have the anchor-based graph learning in this repo? I did not find it here.

Thanks

**Comment by hugochan** [comment]
> Hi,
> 
> Great work. Do you also have the anchor-based graph learning in this repo? I did not find it here.
> 
> Thanks

Thank you for your interest to our work! The implementation of the IDGL-Anch model will be released in this repo soon.

**Comment by hugochan** [comment]
Uploaded the IDGL-Anch code.
