### ISSUE TITLE
about the code of papers

### ISSUE THREAD

**Issue by DMW123** [hugochan/IDGL#7]
Hi， Excuse，is  the code for "Iterative Deep Graph Learning for Graph Neural Networks: Better and Robust Node Embeddings " different form "Deep Iterative and Adaptive Learning for Graph Neural Networks"?
     In the paper "Iterative Deep Graph Learning for Graph Neural Networks: Better and Robust Node Embeddings",you give the implementation: https://github.com/hugochan/IDGL. But, the page of github show  that ,it is for "Deep Iterative and Adaptive Learning for Graph Neural Networks".  I am confused about this.  thanks.

**Comment by hugochan** [comment]
> Hi， Excuse，is the code for "Iterative Deep Graph Learning for Graph Neural Networks: Better and Robust Node Embeddings " different form "Deep Iterative and Adaptive Learning for Graph Neural Networks"?
> In the paper "Iterative Deep Graph Learning for Graph Neural Networks: Better and Robust Node Embeddings",you give the implementation: https://github.com/hugochan/IDGL. But, the page of github show that ,it is for "Deep Iterative and Adaptive Learning for Graph Neural Networks". I am confused about this. thanks.

Thank you for your interest to our work! The new IDGL paper extends the previous work by proposing a scalable version of IDGL, namely, IDGL-Anch. We will update this repo to include code of both models soon.

**Comment by DMW123** [comment]
> Hi， Excuse，is the code for "Iterative Deep Graph Learning for Graph Neural Networks: Better and Robust Node Embeddings " different form "Deep Iterative and Adaptive Learning for Graph Neural Networks"?
> In the paper "Iterative Deep Graph Learning for Graph Neural Networks: Better and Robust Node Embeddings",you give the implementation: https://github.com/hugochan/IDGL. But, the page of github show that ,it is for "Deep Iterative and Adaptive Learning for Graph Neural Networks". I am confused about this. thanks.
