### ISSUE TITLE
out of memory?

### ISSUE THREAD

**Issue by strugglejx** [hugochan/IDGL#8]
Hi:
  i met some errors when i run the codes.  The error messages as following:

datasets and enviroments:
size of datasets: 4000*500, 4000 is the number of nodes and 500 is the number of features. 
GPU memory: 12G

>>> Train Epoch: [9 / 500]
Traceback (most recent call last):
  File "/data0//work/IDGL/src/main.py", line 127, in <module>
    main(config)
  File "/data0//work/IDGL/src/main.py", line 24, in main
    model.train()
  File "/data0/work/IDGL/src/core/model_handler.py", line 148, in train
    self.run_epoch(self.train_loader, training=True, verbose=self.config['verbose'])
  File "/data0/work/IDGL/src/core/model_handler.py", line 744, in _run_whole_epoch
    cur_raw_adj, cur_adj = network.learn_graph(network.graph_learner2, node_vec, network.graph_skip_conn, graph_include_self=network.graph_include_self, init_adj=init_adj)
  File "/data0/work/IDGL/src/core/models/graph_clf.py", line 94, in learn_graph
    raw_adj = graph_learner(node_features)
  File "/.conda/envs/jx_dp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data0/work/IDGL/src/core/layers/graphlearn.py", line 86, in forward
    attention = torch.matmul(context_norm, context_norm.transpose(-1, -2)).mean(0)
RuntimeError: CUDA out of memory. Tried to allocate 330.00 MiB (GPU 4; 10.92 GiB total capacity; 6.50 GiB already allocated; 279.06 MiB free; 6.70 GiB reserved in total by PyTorch)

**Comment by hugochan** [comment]
> Hi:
> i met some errors when i run the codes. The error messages as following:
> 
> datasets and enviroments:
> size of datasets: 4000*500, 4000 is the number of nodes and 500 is the number of features.
> GPU memory: 12G
> 
> > > > Train Epoch: [9 / 500]
> > > > Traceback (most recent call last):
> > > > File "/data0//work/IDGL/src/main.py", line 127, in 
> > > > main(config)
> > > > File "/data0//work/IDGL/src/main.py", line 24, in main
> > > > model.train()
> > > > File "/data0/work/IDGL/src/core/model_handler.py", line 148, in train
> > > > self.run_epoch(self.train_loader, training=True, verbose=self.config['verbose'])
> > > > File "/data0/work/IDGL/src/core/model_handler.py", line 744, in _run_whole_epoch
> > > > cur_raw_adj, cur_adj = network.learn_graph(network.graph_learner2, node_vec, network.graph_skip_conn, graph_include_self=network.graph_include_self, init_adj=init_adj)
> > > > File "/data0/work/IDGL/src/core/models/graph_clf.py", line 94, in learn_graph
> > > > raw_adj = graph_learner(node_features)
> > > > File "/.conda/envs/jx_dp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in **call**
> > > > result = self.forward(*input, **kwargs)
> > > > File "/data0/work/IDGL/src/core/layers/graphlearn.py", line 86, in forward
> > > > attention = torch.matmul(context_norm, context_norm.transpose(-1, -2)).mean(0)
> > > > RuntimeError: CUDA out of memory. Tried to allocate 330.00 MiB (GPU 4; 10.92 GiB total capacity; 6.50 GiB already allocated; 279.06 MiB free; 6.70 GiB reserved in total by PyTorch)

@strugglejx Thank you for your attention to our work! Can you share the run command? And what is the dataset? I was able to run the IDGL model on Citeseer which contains ~3k nodes with 16GB GPU memory. Not sure if 12GB memory is enough for your case.
