### ISSUE TITLE
value of hyper parameter to reproduce the experiment

### ISSUE THREAD

**Issue by lipingcoding** [hugochan/IDGL#9]
It seems that the values of hyper parameters provided in config file could not promise results reported in the paper? Could you provide specific values, especially for smooth ratio, degree ratio, and sparsity ratio

**Comment by hugochan** [comment]
> It seems that the values of hyper parameters provided in config file could not promise results reported in the paper? Could you provide specific values, especially for smooth ratio, degree ratio, and sparsity ratio

@lipingcoding thank you for your interest to our work! We ran multiple runs with different random seeds in our experiments. You may want to do multiple runs with different random seeds. I think the hyperparameteres values in the config files should be updated. Which config file are you specifically referring to?

**Comment by lipingcoding** [comment]
@hugochan For example, in src/config/cora/idgl.yml, the values of both zero. Are they right?

**Comment by lipingcoding** [comment]
sorry, my fault.
